CREATE TABLE `elephant`.`travel_order` (
    `orderid` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单id',
    `travellerid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '游客（拼团）id',
    `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '真实姓名',
    `id` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '证件号码',
	`id_type` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT '证件类型',
    `gender` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT '性别',
    `birthday` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '出生日期',
    `mobile` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '手机',
    `email` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'email',
    `wxid` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '微信号',
    `address` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'qq昵称',
    `emergency_contact` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '紧急联系人',
    `emergency_phone` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '紧急联系电话',
    `groupid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '发团id',
    `start_date` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '开始日期',
    `end_date` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '结束日期',
    `priceid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '价目id',
    `start_place` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出发地点',
    `end_place` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '结束地点',
    `channel` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT '游客渠道',
    `price` DECIMAL(10 , 2 ) NOT NULL DEFAULT 0 COMMENT '定价',
    `status` SMALLINT(4) NOT NULL DEFAULT 0 COMMENT '订单状态:生成,已付款,退款,换人,完成',
    `discountid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '优惠id',
    `refoundid` BIGINT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '退款id',
    `actual_price` DECIMAL(10 , 2 ) NOT NULL DEFAULT 0 COMMENT '实际缴费',
    PRIMARY KEY (`orderid`) COMMENT '主键',
    UNIQUE INDEX `orderid_UNIQUE` (`orderid` ASC) COMMENT '主键',
    INDEX `travellerid_INDEX` (`travellerid` ASC) COMMENT '游客索引',
    INDEX `groupid_INDEX` (`groupid` ASC) COMMENT '发团索引',
    INDEX `priceid_INDEX` (`priceid` ASC) COMMENT '价目索引'
)  ENGINE=INNODB DEFAULT CHARACTER SET=UTF8 COMMENT='订单表';
alter TABLE elephant.travel_order AUTO_INCREMENT=1;